language: java
notifications:
  email: false
  slack:
    secure: ujAPqTESgo6Pq7khbqZhMjHCpniBFRowJmPq2+FFFLU3fy+jY69GLo2FLcmrPBeXxBfDbTyXsuKSfcycTJWmkqPrviezao4F/39Msq2u/+5T1Pgq3193kdZ5HCaWXWWSEZn+6gjPWPj17/aV+NnAEVuxuC4VDiNHB6jynGQhr0DkyqmrBXo/efq5PjYf5v1zjwN4XCdovXPdToJv7/c6BZGLC/XcHwwhD/H//7pR5GzTTF7JgWi2j0zzzNpgC0mHE/Bs9R95SfQJEGsov08BbaJkw4tGfyBxF908NFLqpXZgDdKijlHcvBXyUYh8ccMu+V5zGcCc7ll1jMsBa1jSyixiHpIk8FnyYKl3pEwXAR0lm4MAWKK0EEL2plqP/TCzDtTzFBeliQydPKtuKPyVBeANQwWIkmn0EuhEbbvwdc456fUuLP/0mgbxC0CnFB3iETFciLPJuqLkdisXcdnEcIlOfuDiVQOSrHfIAgzS2xjjoUzeqyMUqcI1FDtG/EW3sIUlVBCRkeVpkfUg57f0qHjdvxkH7FhMveofq8Y7bNvmak0h2S6TMxiiOQ5fhHJJcL4s/ukXpb3Fkr4+Wwq5mz3vTn8t/9AF2CMB3WyVqja4LoWiKS+TaorHdWZuZa9GCblYoVdqdBCRPWPkt+VDZvH077/Mfklpcqw0C6ZANxE=
jdk:
- oraclejdk8
install: echo 'Run Maven Tests'
script: mvn clean install --settings .travis/settings.xml -Dmaven.javadoc.skip=true -U
  -B -V
after_success: mvn deploy --settings .travis/settings.xml -DskipTests -B -V
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: YCeE6Ku5JMHiE/x8eZPXG20yc+w6llDz6mF+5+liZxwdn6iDy8pAhI5CjesmVr8UgRjqL+n9DPdUwC7KceuTUKSllApXpOUu6I1RQSgPOLaEP7dCaSQbJ0NJSc4+HeDVJKHtjqZUBoftc8g70/5qGARoI0yURV7onWWxukWl2rPlWf6J5qJLheiFux6X6Besz/7ruUzOA7OJDBuCl4Ilw1yRnIbvbgrqPiKftRzf3pB9ArdO+M8T6XLwv5pojjOZ0NydeTuF/b7K3Oua3BRYvLM9yJrMrwPSsYM8ImrYmSCtvERfpPezCsO2epZo8gGtDb0dHAxS63zCjG9IYEbo0KBqABLnRH/qQf11rs+i3A0UXo8IZ05jo5qYlKdJb3TDHi9beWnQc3e3h09xutskuX4btJzkc1nxPGQ1vAhnOyKrrwg2bXdjuiRnJnqcIwTnIUKS4hqQX4KNBm/V47BCw++pHj0V2weZpaFmNyVLPzn17IOgqtSsJZvOI5X7Ug2BqDZi3uZuoQsyjOxt884wlj0nePkykyT1Dq6J3aK4vuoQwcoE4w/c/bKAfmsUftTpH5rL559ACnyWMmp75We7QTU9Q3Qc0ilNYf6esFWZmCBKWYpZ1C8SspfkrUbAv1nKPTTABh4LT0VJnwyF97g9/w4X+XjW83cCr6ux7kSFN+g=
  - secure: MdG3VB3P4xztuC8lpLuSzZhIv1lc/Zh0/5HPUIuDl1pv7JaVAu72Tg6UyXiAVdw1BniymQQD+BckesnXzc2m42gqCdyGshsrvgGYKSr+tcWPyTC+ii1L9xV8U99zzx9jOJzQ3DEXglDvDQ4HM8bgiAvNH6zsjkFY0x41bsmqEqB1uAet12BPyh7QOH8Yv+D0stF13yy/ywvq5h8aQp7+0jd+Tt5ssfI2IZZGsrLMsQI33lkyuKScKqQPw3u3RFK3jb3VPNwaSFis6NVc3iQPM5V6J+sYATeaMY7Hcd7pVtBJPSC8LNWC+kRxfmqe1J+Hh29u7zZHRg5+dSdp6Nk9Z+rBqbUqxTTF9tuI0oKWPyJhgQf7FFR3L1UuZYZF4o0ggFQKcMiFuwD+BYtsS6BhViKVymjgljQjcjv4nuBNkjVWzhsMkVi8p1QT72/e0shX8GpWOxd1r3c4UQhMEXKjyN+l8MHW6wVrgFbwxwOw47WvjbcSQUs2CRUcl+fblzsz0uxmSYSYFCLCdxxzjHMmAUijsjfTPZBc8mb6YO5cjDTrGlBFXPlgMZwlD6J7R/yHwCrJpd72vNgMRutXCLW3lmA7BhF52ugPq2YhIloQKONwAF2lc0ykhSAGTSKL2viSHSV6uyNy6lpUgd6egE99gUTqr5QpoHsaBI1btelHLp0=
